In [1]:
import numpy as np
import pandas as pd

In [2]:
#Sample labels
labelsamples= ["b1p1_m05","b1p1_m10","b1p1_m20","b1p1_m40","b1p5_m05","b1p5_m10","b1p5_m20","b1p5_m40","b10_m05","b10_m10","b10_m20","b10_m40"]

path='/home/leoperes/Desktop/UpperLimitCodeBDMv4/UpperLimitCodeBDM/Optimization/NuclearModelsOptSelectionApplication_final/generated/20260512_100838/'
#txt files with signal strength, expected background and signal efficiency for each nuclear configuration model
infiles = ['hA_BR/Eff_Bkg_index_00a.txt', 'hA_LFG/Eff_Bkg_index_01a.txt', 'hA_ESF/Eff_Bkg_index_02a.txt', 'hN_BR/Eff_Bkg_index_00b.txt', 'hN_LFG/Eff_Bkg_index_01b.txt', 'hN_ESF/Eff_Bkg_index_02b.txt']

#function to read the list of txt files
def readtxt(infile_array):
    listloaded = [] 
    for infile in infile_array:
        listloaded.append(np.loadtxt(path+infile, usecols=(4,5), skiprows=1))
    return listloaded

In [3]:
optimals = readtxt(infiles)

## 1: (b_cv - b_i)/b_cv ,   2: (eff_cv - eff_i)/eff_cv ##

In [4]:
def return_shift(value):
    if value < 1:
        return -1+value
    if value > 1:
        return value-1
    if value == 1:
        return value-1

In [5]:
optimals = np.array(optimals)
optimals

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

In [6]:
# Vectorize the function
vectorized_nuclear_shift = np.vectorize(return_shift)

In [7]:
def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'blue' if val > 0 else 'black'
    return 'color: % s' % color

models = [vectorized_nuclear_shift(optimals[i][:][:]/optimals[0][:][:]) for i in range(6) ] 
df_models = [pd.DataFrame({'Efficiency Shift': model[:, 0]*100, 'Background Shift': model[:, 1]*100}) for model in models]

In [8]:
df_models[2]

    Efficiency Shift  Background Shift
0          32.784524          2.310924
1          25.061119          2.631579
2          43.091503          2.051282
3          33.857729          2.796053
4          -0.223797         -1.392707
5           2.811517         -1.392707
6           1.139623         -1.392707
7           3.262323         -1.392707
8           0.273936         -0.512258
9           1.180710          0.343224
10        -22.770420         -0.207867
11          0.518307          0.343224

In [9]:
df_models[1]

    Efficiency Shift  Background Shift
0          -7.413648          8.193277
1         -10.779674          7.807018
2          -4.850791          7.545788
3          -6.908345          8.634868
4           2.284595         -2.767088
5           2.651183         -2.767088
6           1.253672         -2.767088
7           1.245771         -2.767088
8           0.011524         -0.704354
9          -0.133347         -0.243578
10       -100.000000       -100.000000
11          0.291061         -0.243578

In [10]:
df_models[0].to_latex(index=False)

'\\begin{tabular}{rr}\n\\toprule\nEfficiency Shift & Background Shift \\\\\n\\midrule\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n0.000000 & 0.000000 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [11]:
print(df_models[5].to_latex(index=False))

\begin{tabular}{rr}
\toprule
Efficiency Shift & Background Shift \\
\midrule
-7.953446 & 0.525210 \\
-13.228519 & 2.017544 \\
-3.452364 & 0.000000 \\
-10.054720 & 0.904605 \\
3.777453 & -0.751329 \\
4.327120 & -0.751329 \\
6.720507 & -0.751329 \\
5.128478 & -0.751329 \\
-2.712498 & -1.051958 \\
-1.029730 & -1.173605 \\
-24.931222 & -1.934762 \\
-1.839616 & -1.173605 \\
\bottomrule
\end{tabular}

&$m_\chi$ (GeV)}& hA\_BR & hA\_LFG & hA\_ESF  & hN\_BR  & hN\_LFG  & hN\_ESF  \\
\hline
\multirow{4}{*}{$\gamma = 1.1$}& 5 &0.015 & -6.6\%  & +53\%  &  &  & \\
  &10& 0.018&-11.1\%& +44\%  &  &  &   \\
  &20&0.018 &0\%  & +54\% & +55\%  &  &   \\
  &40&0.019 & -5.2\%&  &  & +47% &   \\
\hline
\multirow{4}{*}{$\gamma = 1.5$}& 5 &0.113  &+2.6\%  &  &  &  & \\
  &10& 0.115& 1.73\% &  &  &  &   \\
  &20& 0.118& 1.69\% &  &  &  &   \\
  &40& 0.118& 1.69\%  &  &  &  &   \\
  \hline
\multirow{4}{*}{$\gamma = 10$}& 5 & 0.373 &0.0\%  &  &  &  & \\
  &10&0.387 & -0.25\%&  &  &  &   \\
  &20& 0.402& X &  &  &  &   \\
  &40& 0.332& -4.8\%&  &  &  &   \\
\hline


53.333333
44.444444
55.555556
47.368421
-0.884956
1.739130
1.694915
3.389831
0.268097
1.033592
-21.890547
0.602410

 & 11.153310 \\
 & 11.136119 \\
 & 11.136119 \\
 & 11.120641 \\
 & 10.428919 \\
 & 10.428919 \\
 & 10.428919 \\
 & 10.428919 \\
 & 7.396272 \\
 & 7.293977 \\
 & 5.610628 \\
 & 6.409939 \\

In [15]:
print(df_models)

[    Efficiency Shift  Background Shift
0                0.0               0.0
1                0.0               0.0
2                0.0               0.0
3                0.0               0.0
4                0.0               0.0
5                0.0               0.0
6                0.0               0.0
7                0.0               0.0
8                0.0               0.0
9                0.0               0.0
10               0.0               0.0
11               0.0               0.0,     Efficiency Shift  Background Shift
0          -7.413648          8.193277
1         -10.779674          7.807018
2          -4.850791          7.545788
3          -6.908345          8.634868
4           2.284595         -2.767088
5           2.651183         -2.767088
6           1.253672         -2.767088
7           1.245771         -2.767088
8           0.011524         -0.704354
9          -0.133347         -0.243578
10       -100.000000       -100.000000
11          0.291061         -0.243578,     Efficiency Shift  Background Shift
0          32.784524          2.310924
1          25.061119          2.631579
2          43.091503          2.051282
3          33.857729          2.796053
4          -0.223797         -1.392707
5           2.811517         -1.392707
6           1.139623         -1.392707
7           3.262323         -1.392707
8           0.273936         -0.512258
9           1.180710          0.343224
10        -22.770420         -0.207867
11          0.518307          0.343224,     Efficiency Shift  Background Shift
0         -52.305622          6.407563
1         -48.315180          6.754386
2         -46.189989          5.054945
3         -42.622052          6.661184
4           1.777538         -2.602162
5           4.256186         -2.602162
6           2.422031         -2.602162
7           2.287965         -2.602162
8          -1.439540         -2.213685
9          -1.231648         -2.158990
10        -24.242304         -2.078670
11         -1.798268         -2.158990,     Efficiency Shift  Background Shift
0         -55.855097          2.205882
1         -57.744155          3.157895
2         -52.977432          1.611722
3         -53.513133          2.713816
4           6.680335         -2.400586
5           5.054845         -2.400586
6           4.397226         -2.400586
7           3.112423         -2.400586
8          -0.791237         -1.609952
9          -0.928131         -1.483614
10        -24.317965         -0.031980
11         -1.702480         -1.483614,     Efficiency Shift  Background Shift
0          -7.953446          0.525210
1         -13.228519          2.017544
2          -3.452364          0.000000
3         -10.054720          0.904605
4           3.777453         -0.751329
5           4.327120         -0.751329
6           6.720507         -0.751329
7           5.128478         -0.751329
8          -2.712498         -1.051958
9          -1.029730         -1.173605
10        -24.931222         -1.934762
11         -1.839616         -1.173605]